# Generated by Django 5.2.6 on 2026-03-21 16:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("users", "0003_rename_updated_at_user_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects_created",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                ],
                default="PLANNED",
                max_length=20,
            ),
        ),
    ]
