# Generated by Django 5.2.6 on 2026-03-21 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_created_at_user_updated_at_alter_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="updated_At",
            new_name="updated_at",
        ),
    ]
