# Generated by Django 5.2.6 on 2026-03-21 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_created_at_alter_project_created_by_and_more"),
        ("tasks", "0002_alter_task_priority_alter_task_status"),
        ("users", "0003_rename_updated_at_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tasks",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(default="MEDIUM", max_length=20),
        ),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projects.project",
            ),
        ),
    ]
